export enum STORE_STATE {
  INITIAL = 'INITIAL',
  PENDING_BROWSER_STORAGE = 'PENDING_BROWSER_STORAGE',
  PENDING_REMOTE = 'PENDING_REMOTE',
  FULLFILLED = 'FULLFILLED',
  ERROR = 'ERROR',
  CLEARED = 'CLEARED',
}
